# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-11 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0002_auto_20181211_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('post', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('photo_image', models.ImageField(upload_to='photos/')),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleria.Blogger')),
                ('tags', models.ManyToManyField(to='galleria.tags')),
            ],
        ),
    ]
